apiVersion: v1
kind: ConfigMap
metadata:
  name: azureopenai-config
data:
  title: "Azure OpenAI App running on Azure Red Hat OpenShift"
  description: "Microsoft GBB TEAM and Source Code Red Hat Team"
  port: "8080"
  deployment_name: "gpt-35-turbo"
  api_type: "azure"
  api_version: "2023-05-15"
