apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: azureopenai-aro-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi # Specify the desired storage size
