apiVersion: v1
kind: Service
metadata:
  labels:
    app: aro-azureopenai
  name: aro-azureopenai-svc
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: aro-azureopenai
  sessionAffinity: None
  type: ClusterIP
