apiVersion: v1
kind: ConfigMap
metadata:
  name: azureopenai-config
data:
  title: "Azure OpenAI App running in Azure Red Hat OpenShift"
  description: "Azure OpenAI App running in Azure Red Hat OpenShift"
  port: "8080"